from django.conf.urls import url
from myworkflows.views import *
from django.contrib import admin

urlpatterns = [
    url(r'^workflow_list/$', workflow, name='工单列表'),
    url(r'^test_load/$', test_load, name='测试'),
    url(r'^add_server_permission/$', add_server_permission, name='添加服务器权限'),
    url(r'^failure_declare_finish/$', failure_declare_finish, name='设置电脑故障申请完成'),
    url(r'^data_workflow_list/$', data_workflow_list, name='工单列表数据'),
    url(r'^workflow_template/$', workflow_template, name='工单模板'),
    url(r'^get_workflow_state/$', get_workflow_state, name='流程步骤'),
    url(r'^start_workflow/$', start_workflow, name='开始流程'),
    url(r'^apply_history/$', apply_history, name='申请流程历史页面'),
    url(r'^apply_history_all/$', apply_history_all, name='申请流程汇总页面'),
    url(r'^data_apply_history/$', data_apply_history, name='申请流程历史数据'),
    url(r'^data_apply_history_all/$', data_apply_history_all, name='申请流程汇总数据'),
    url(r'^game_server_list/$', game_server_list, name='区服列表页面'),
    url(r'^game_server_list_api/$', game_server_list_api, name='区服列表api文档'),
    url(r'^data_game_server_list/$', data_game_server_list, name='区服列表页面数据'),
    url(r'^add_or_edit_svn_scheme/$', add_or_edit_svn_scheme, name='增加或者修改svn方案'),
    url(r'^get_svn_scheme/$', get_svn_scheme, name='获取svn方案'),
    url(r'^del_svn_scheme/$', del_svn_scheme, name='删除svn方案'),
    url(r'^data_svn_scheme/$', data_svn_scheme, name='svn方案数据'),
    url(r'^approve_list/$', approve_list, name='我的待审批列表页面'),
    url(r'^svn_scheme_detail/$', svn_scheme_detail, name='方案明细'),
    url(r'^add_or_edit_svn_scheme_detail/$', add_or_edit_svn_scheme_detail, name='方案明细'),
    url(r'^data_svn_scheme_detail/$', data_svn_scheme_detail, name='svn方案数据'),
    url(r'^get_svn_scheme_detail/$', get_svn_scheme_detail, name='svn方案数据'),
    url(r'^del_svn_scheme_detail/$', del_svn_scheme_detail, name='svn方案数据'),
    url(r'^data_approve_list/$', data_approve_list, name='我的待审批列表数据'),
    url(r'^approved_list/$', approved_list, name='我的审批记录列表页面'),
    url(r'^data_approved_list/$', data_approved_list, name='我的审批记录列表数据'),
    url(r'^workflow_approve/$', workflow_approve, name='审批'),
    url(r'^myworkflow/$', myworkflow, name='我的申请历史某个详细'),
    url(r'^myworkflow_history/$', myworkflow_history, name='我的申请历史,返回content_obj'),
    url(r'^myworkflow_hotupdate/$', myworkflow_hotupdate, name='从热更新中查看'),
    url(r'^workflow_state_approve_process/$', workflow_state_approve_process, name='获取流程进度'),
    url(r'^get_workflow_approve_user/$', get_workflow_approve_user, name='获取流程的审批用户'),
    url(r'^send_mail_for_wse/$', send_mail_for_wse, name='给wse发送邮件通知'),
    url(r'^SVNDOC/$', svn_doc, name='SVN申请说明'),
    url(r'^del_myworkflow_(svn)/$', del_myworkflow_obj, name='del_myworkflow_obj'),
    url(r'^list_svn_repo/$', list_svn_repo, name='下拉展示SVN仓库'),
    url(r'^list_svn_scheme/$', list_svn_scheme, name='下拉展示SVN方案'),
    url(r'^list_workflow/$', list_workflow, name='下拉展示workflow'),
    url(r'^list_game_project/$', list_game_project, name='下拉项目从mysql中查询'),
    url(r'^list_game_project_by_group/$', list_game_project_by_group, name='根据部门来选择项目'),
    url(r'^list_game_project_area/$', list_game_project_area, name='根据项目选择地区'),
    url(r'^list_game_project_area_detail/$', list_game_project_area_detail, name='根据项目选择地区'),
    url(r'^list_game_client_version/$', list_game_client_version, name='下拉展示前端版本'),
    url(r'^list_game_server_version/$', list_game_server_version, name='下拉展示后端版本'),
    url(r'^list_cdnurl/$', list_cdnurl, name='下拉cdn url从mysql中查询'),
    url(r'^svn_perm_scheme/$', svn_perm_scheme, name='SVN权限方案列表'),
    url(r'^get_svn_scheme_data/$', get_svn_scheme_data, name='svn方案的全部明细'),
    url(r'^get_server_tree/$', get_server_tree, name='区服列表'),
    url(r'^get_server_list_by_cdn/$', get_server_list_by_cdn, name='根据cdn获取区服列表'),
    url(r'^get_project_server_tree/$', get_project_server_tree, name='项目区服列表'),
    url(r'^transfer_to_other_admin/$', transfer_to_other_admin, name='故障工单转交给其他网管处理'),
    url(r'^get_cnd_version_list/$', get_cnd_version_list, name='获取前端cdn和版本号的组合'),
    url(r'^get_project_area_lock/$', get_project_area_lock, name='获取项目和地区的锁'),
    url(r'^ops_manager_lock/$', ops_manager_lock, name='项目和地区的锁'),
    url(r'^game_server_ops_manager_lock/$', game_server_ops_manager_lock, name='项目和地区的锁'),
    url(r'^data_project_area_lock/$', data_project_area_lock, name='项目和地区的锁data'),
    url(r'^get_one_project_area_lock/$', get_one_project_area_lock, name='获取项目和地区的锁'),
    url(r'^edit_one_project_area_lock/$', edit_one_project_area_lock, name='修改项目和地区的锁'),

    url(r'^hot_client_list/$', hot_client_list, name='前端热更新任务'),
    url(r'^data_hot_client_list/$', data_hot_client_list, name='前端热更新任务数据'),
    url(r'^get_hot_client_task/$', get_hot_client_task, name='获取前端热更新任务'),
    url(r'^edit_hot_client_task/$', edit_hot_client_task, name='修改前端热更新任务'),
    url(r'^execute_hot_client_task/$', execute_hot_client_task, name='执行前端热更新任务'),

    url(r'^hot_server_list/$', hot_server_list, name='后端热更新任务'),
    url(r'^data_hot_server_list/$', data_hot_server_list, name='后端热更新任务数据'),
    url(r'^get_hot_server_task/$', get_hot_server_task, name='获取后端热更新任务'),
    url(r'^edit_hot_server_task/$', edit_hot_server_task, name='修改后端热更新任务'),
    url(r'^execute_hot_server_task/$', execute_hot_server_task, name='执行后端热更新任务'),
    url(r'^host_server_detail/$', host_server_detail, name='后端热更新的详细区服'),
    url(r'^data_host_server_detail/$', data_host_server_detail, name='后端热更新的详细区服数据'),

    url(r'^get_client_type/$', get_client_type, name='获取客户端的类型，安卓或者iOS'),
    url(r'^get_hot_server_process$', get_hot_server_process, name='获取后端热更新的进度'),

    url(r'^upload_hot_server/$', upload_hot_server, name='上传热更新文件'),

    url(r'^list_project_group_user/$', list_project_group_user, name='选择项目和分组下面的用户'),
    url(r'^list_pair_code/$', list_pair_code, name='下拉选择已经创建好的热更新绑定代号'),

    url(r'^list_project_related_ops/$', list_project_related_ops, name='选择项目相关的运维人员'),
    url(r'^get_pair_code_order_available$', get_pair_code_order_available, name='根据项目地区和绑定代号以及先后顺序判断可用性'),

    url(r'^pull_file_list/$', pull_file_list, name='获取版本接收机文件列表'),

    url(r'^myhotupdate/$', myhotupdate, name='某个热更新具体详细页面'),
    url(r'^data_myhotupdate/$', data_myhotupdate, name='某个热更新具体详细数据'),
    url(r'^data_myhotupdate_block/$', data_myhotupdate_block, name='某个热更新之前的任务,查看阻塞情况'),

    url(r'^version_update_summarize/$', version_update_summarize, name='热更新汇总工单页面'),
    url(r'^data_version_update_summarize/$', data_version_update_summarize, name='热更新汇总工单数据'),

    url(r'^hot_update_api/$', hot_update_api, name='热更新文档'),

    url(r'^change_approve/$', change_approve, name='更改审批人'),

    url(r'^help_doc$', help_doc, name='工单使用帮助'),

    url(r'^real_time_log$', real_time_log, name='实时log'),

    url(r'^game_server_type/$', game_server_type, name='区服类型页面'),
    url(r'^data_game_server_type/$', data_game_server_type, name='区服类型数据'),
    url(r'^add_or_edit_game_server_type/$', add_or_edit_game_server_type, name='添加区服类型数据'),
    url(r'^get_game_server_type/$', get_game_server_type, name='添加区服类型数据'),
    url(r'^del_game_server_type/$', del_game_server_type, name='删除区服类型数据'),

    url(r'^hotupdate_cmdb_log$', hotupdate_cmdb_log, name='cmdb热更新log'),

    url(r'^start_hotupdate$', start_hotupdate, name='热更新页面'),
    url(r'^hotupdate_email_approve_help_doc$', hotupdate_email_approve_help_doc, name='SVN申请说明'),

    url(r'^get_remote_cdn/$', get_remote_cdn, name='从web后台获取cdn'),

    url(r'^get_hotupdate_client_type/$', get_hotupdate_client_type, name='获取前端热更新客户端类型'),
    url(r'^get_cdn_root_url/$', get_cdn_root_url, name='获取前端热更新cdn根路径'),
    url(r'^get_cdn_dir/$', get_cdn_dir, name='获取前端热更新cdn目录'),

    url(r'^download_hotupdate/$', download_hotupdate, name='导出热更新excel的功能'),
    url(r'^get_csxy_game_server_platform/$', get_csxy_game_server_platform, name='获取超神的平台'),
    url(r'^get_csxy_type/$', get_csxy_type, name='获取超神的类型'),
    url(r'^svn_repo/$', svn_repo, name='SVN仓库页面'),
    url(r'^data_svn_repo/$', data_svn_repo, name='SVN仓库数据'),
    url(r'^get_svn_repo/$', get_svn_repo, name='获取svn编辑数据'),
    url(r'^add_or_edit_repo/$', add_or_edit_repo, name='增加或编辑svn仓库'),
    url(r'^del_svn_repo/$', del_svn_repo, name='删除svn仓库'),

    url(r'^game_server_install/$', game_server_install, name='区服安装'),
    url(r'^list_game_server/$', list_game_server, name='区服列表'),
    url(r'^list_area_name_by_project/$', list_area_name_by_project, name='区服列表'),
    url(r'^game_server_action/$', game_server_action, name='区服管理动作'),
    url(r'^get_cdn_list/$', get_cdn_list, name='根据项目和地区获取CDN列表'),
    url(r'^list_cdn_root_url/$', list_cdn_root_url, name='根据项目和地区获取CDN根目录列表'),
    url(r'^game_server_action_record/$', game_server_action_record, name='区服管理操作记录'),
    url(r'^data_game_server_action_record/$', data_game_server_action_record, name='区服管理操作记录数据'),
    url(r'^celery_worker_status/$', celery_worker_status, name='celery worker状态列表'),
    url(r'^sync_running_worker/$', sync_running_worker, name='同步运行中的worker'),
    url(r'^save_celery_notice_receive_user/$', save_celery_notice_receive_user, name='保存celery告警接收人员'),
    url(r'^get_celery_notice_receive_user/$', get_celery_notice_receive_user, name='获取celery告警接收人员'),
    url(r'^delete_worker_monitor/$', delete_worker_monitor, name='取消需要监控的worker'),
    url(r'^list_room_name_by_project/$', list_room_name_by_project, name='根据项目列出机房'),
    url(r'^host_compression_apply/$', host_compression_apply, name='主机迁服/回收申请提交'),
    url(r'^host_compression_apply_list/$', host_compression_apply_list, name='主机迁服/回收申请记录列表页'),
    url(r'^data_host_compression_apply_list/$', data_host_compression_apply_list, name='主机迁服/回收申请记录数据'),
    url(r'^host_compression_apply_detail/(?P<apply_id>[0-9]+)/$', host_compression_apply_detail, name='主机迁服/回收申请详情'),
    url(r'^edit_host_compression_apply/$', edit_host_compression_apply, name='修改主机迁服/回收申请单状态'),
    url(r'^get_data_host_compression_apply/$', get_data_host_compression_apply, name='获取主机迁服/回收申请单编辑数据'),
    url(r'^list_host_compression_type/$', list_host_compression_type, name='列出主机迁服/回收申请的操作类型'),
    url(r'^list_host_compression_action_status/$', list_host_compression_action_status, name='列出主机迁服状态'),
    url(r'^list_host_compression_recover_status/$', list_host_compression_recover_status, name='列出主机回收状态'),
    url(r'^execute_host_compression/$', execute_host_compression, name='手动主机迁服/回收任务'),
    url(r'^get_game_server_list/$', get_game_server_list, name='根据cdn域名和目录获取区服数据'),
    url(r'^host_compression_cmdb_log/(?P<id>[0-9]+)/$', host_compression_cmdb_log, name='主机迁服回收日志页面'),
    url(r'^game_server_off_callback_api_doc/$', game_server_off_callback_api_doc, name='项目下架回调接口文档'),
    url(r'^workflow_node_config/(?P<workflow_id>[0-9]+)/$', workflow_node_config, name='workflow_node_config'),
    # 流程状态配置
    url(r'^change_workflow_explain/(?P<workflow_id>[0-9]+)/$', change_workflow_explain, name='修改工单流程描述说明'),
    url(r'^list_state_by_workflow/$', list_state_by_workflow, name='根据流程id列出所有流程状态'),
    url(r'^list_all_state/$', list_all_state, name='根列出所有流程状态'),
    url(r'^add_workflow_state/$', add_workflow_state, name='保存新增或者编辑的流程状态信息'),
    url(r'^del_state/$', del_state, name='删除流程状态'),
    url(r'^edit_workflow_state/$', edit_workflow_state, name='编辑流程审核步骤'),
    url(r'^project_celery_queue_map/$', project_celery_queue_map, name='项目与celery任务队列关系'),
    url(r'^data_project_celery_queue_map/$', data_project_celery_queue_map, name='项目与celery任务队列关系数据'),
    url(r'^add_or_edit_project_celery_queue_map/$', add_or_edit_project_celery_queue_map, name='增加或者编辑项目和celery队列关系'),
    url(r'^get_project_celery_queue_map/$', get_project_celery_queue_map, name='获取项目与celery队列关系编辑数据'),
    url(r'^delete_get_cdn_list_api/$', delete_get_cdn_list_api, name='删除项目与celery队列关系信息'),
    url(r'^get_reject_transition_id/$', get_reject_transition_id, name='根据wse获取拒绝条件的transition id'),
    url(r'^workflow_state_specified_user/$', workflow_state_specified_user, name='流程状态指定用户'),
    url(r'^list_workflow/$', list_workflow, name='列出所有流程'),
    url(r'^list_workflow_state/$', list_workflow_state, name='根据workflow列出state'),
    url(r'^add_or_edit_specified_user/$', add_or_edit_specified_user, name='增加或者编辑流程额外审批人'),
    url(r'^get_state_specified_user/$', get_state_specified_user, name='获取流程状态节点额外审批人编辑数据'),
    url(r'^delete_specified_user/$', delete_specified_user, name='删除流程节点额外审批人信息'),
    url(r'^special_user_config/$', special_user_config, name='工单流程特殊人员配置页'),
    url(r'^add_or_edit_special_user/$', add_or_edit_special_user, name='增加或者编辑流程特殊人员配置信息'),
    url(r'^get_workflow_special_user/$', get_workflow_special_user, name='获取工单流程特殊人员配置信息'),
    url(r'^delete_workflow_special_user/$', delete_workflow_special_user, name='删除工单流程中特殊人员配置'),
    url(r'^list_game_project_by_area/$', list_game_project_by_area, name='根据地区列出游戏项目'),
    url(r'^list_room_name_by_project_and_area/$', list_room_name_by_project_and_area, name='根据项目和地区列出机房'),
    url(r'^cmdb_hotupdate_join_project_doc/$', cmdb_hotupdate_join_project_doc, name='cmdb热更新对接新项目文档'),
    url(r'^execute_add_mac_to_wifi/$', execute_add_mac_to_wifi, name='执行添加mac地址到wifi'),
    url(r'^get_game_server_action_history/$', get_game_server_action_history, name='获取区服操作历史记录'),
    url(r'^cmdb_game_server_action_callback_api_doc/$', cmdb_game_server_action_callback_api_doc,
        name='cmdb区服管理操作回调api文档'),
    url(r'^game_server_migrate/$', game_server_migrate, name='单个区服迁服操作'),
    url(r'^list_celery_worker/$', list_celery_worker, name='下拉展示celery worker'),
    url(r'^list_celery_queue/$', list_celery_queue, name='下拉展示celery queue'),
    url(r'^change_workflow_apply_valid_status/$', change_workflow_apply_valid_status, name='设置工单是否有效'),
    url(r'^wechat_account_transfer/$', wechat_account_transfer, name='cmdb帐号与企业微信帐号转换'),
    url(r'^add_or_edit_wechat_account_transer/$', add_or_edit_wechat_account_transer, name='增加或者编辑cmdb帐号与企业微信的转换关系'),
    url(r'^get_wechat_account_transfer/$', get_wechat_account_transfer, name='获取cmdb与企业微信帐号转换关系数据'),
    url(r'^delete_wechat_account_transfer/$', delete_wechat_account_transfer, name='删除cmdb与企业微信帐号转换的数据'),
    url(r'^hotupdate_templates_bind/(?P<project_id>[0-9]+)/$', hotupdate_templates_bind, name='热更新工单模板绑定'),
    url(r'^save_project_relate_hotupdate_template/$', save_project_relate_hotupdate_template, name='保存项目关联热更新模板'),
    url(r'^list_room_name_by_project_from_host/$', list_room_name_by_project_from_host, name='根据项目通过主机列出机房'),
    url(r'^check_webapi_client_type/$', check_webapi_client_type, name='根据项目和地区获取是否有配置客户端类型'),
    url(r'^version_update_check_push_dir/$', version_update_check_push_dir, name='版本更新单-根据前后段版本号检查推送目录是否存在'),
    url(r'^do_version_update/$', do_version_update, name='手动执行版本更新请求'),
    url(r'^recv_web_maintenance_api_doc/$', recv_web_maintenance_api_doc, name='接收web挂维护通知api文档'),
    url(r'^version_update_plan_doc/$', version_update_plan_doc, name='获取版本更新计划API文档'),
]
