from django.conf.urls import url
from ops.views import *

urlpatterns = [
    url(r'^install_gameserver_list/$', install_gameserver_list, name='开服计划列表'),
    url(r'^data_install_gameserver_list/$', data_install_gameserver_list, name='开服计划列表数据'),
    url(r'^install_gameserver_api/$', install_gameserver_api, name='WEB开服计划文档'),
    url(r'^get_install_game/$', get_install_game, name='获取开服计划，用于修改页面'),
    url(r'^edit_install_game/$', edit_install_game, name='修改开服计划'),
    url(r'^game_install/$', game_install, name='开始装服'),
    url(r'^game_uninstall/$', game_uninstall, name='开始卸服'),
    url(r'^install_gameserver_record_list/$', install_game_server_record, name='开服计划操作记录'),
    url(r'^game_server_off_list/$', game_server_off_list, name='游戏区服下线计划列表页面'),
    url(r'^data_game_server_off_list/$', data_game_server_off_list, name='游戏区服下线计划列表数据'),
    url(r'^get_data_game_server_off/$', get_data_game_server_off, name='获取区服下线假话数据'),
    url(r'^list_game_server_off_status/$', list_game_server_off_status, name='列出区服下线任务所有可用状态'),
    url(r'^edit_game_server_off/$', edit_game_server_off, name='修改区服下线计划'),
    url(r'^execute_game_server_off/$', execute_game_server_off, name='手动执行区服下线计划'),
    url(r'^game_server_off_detail/(?P<id>[0-9]+)/$', game_server_off_detail, name='区服下线计划详情'),
    url(r'^game_server_off_cmdb_log/(?P<id>[0-9]+)/$', game_server_off_cmdb_log, name='区服下线任务日志'),
    url(r'^cmdb_add_gameserveroff_doc/$', cmdb_add_gameserveroff_doc, name='cmdb增加区服下架计划文档'),
    url(r'^modify_srv_open_time_schedule_list/$', modify_srv_open_time_schedule_list, name='修改开服时间计划列表页面'),
    url(r'^data_modify_srv_open_time_schedule_list/$', data_modify_srv_open_time_schedule_list, name='修改开服时间计划列表数据'),
    url(r'^get_data_modify_srv_open_time_schedule/$', get_data_modify_srv_open_time_schedule, name='获取修改开服时间计划数据'),
    url(r'^list_modify_srv_open_time_schedule_status/$', list_modify_srv_open_time_schedule_status,
        name='列出修改开服时间计划所有可用状态'),
    url(r'^edit_modify_srv_open_time_schedule/$', edit_modify_srv_open_time_schedule, name='修改修改开副时间计划'),
    url(r'^modify_srv_open_time_schedule_detail/(?P<id>[0-9]+)/$', modify_srv_open_time_schedule_detail,
        name='修改开服时间计划详情'),
    url(r'^modify_srv_open_time_schedule_cmdb_log/(?P<id>[0-9]+)/$', modify_srv_open_time_schedule_cmdb_log,
        name='修改开服时间计划日志'),
    url(r'^execute_modify_srv_open_time_schedule/$', execute_modify_srv_open_time_schedule, name='手动执行修改开服时间请求'),
    url(r'^cmdb_modsrv_opentime_api_doc/$', cmdb_modsrv_opentime_api_doc, name='cmdb修改开服时间api文档'),
    url(r'^cmdb_modsrv_opentime_callback_api_doc/$', cmdb_modsrv_opentime_callback_api_doc, name='cmdb修改开服时间回调api文档'),
    url(r'^game_server_merge_list/$', game_server_merge_list, name='区服合并列表页面'),
    url(r'^data_game_server_merge_list/$', data_game_server_merge_list, name='区服合并列表数据'),
    url(r'^get_edit_data_game_server_merge/$', get_edit_data_game_server_merge, name='获取合服计划编辑数据'),
    url(r'^edit_game_server_merge_status/$', edit_game_server_merge_status, name='修改合服计划状态'),
    url(r'^cmdb_game_server_merge_api_doc/$', cmdb_game_server_merge_api_doc, name='cmdb接收web合服计划接口文档'),
    url(r'^execute_game_server_merge_schedule/$', execute_game_server_merge_schedule, name='发送合服计划'),
    url(r'^rollback_game_server_merge_schedule/$', rollback_game_server_merge_schedule, name='回滚合服计划'),
    url(r'^in_or_uninstall_gamesrv_callback_api_doc/$', in_or_uninstall_gamesrv_callback_api_doc, name='装/卸区服回调API文档'),
    url(r'^cmdb_release_doc/$', cmdb_release_doc, name='cmdb部署文档'),
]
